### PR TITLE
Fix/rustfmt and test build

### PR DESCRIPTION
**Pull request by stevelr**

### CODE REVIEW

**Comment by autodidaddict** [comment]
Do we know why rust check failed on this?

**Review by brooksmtownsend — DISMISSED** [review]
Looks like the Factorial provider depends on NATS for its tests, @stevelr just refer to https://github.com/wasmCloud/capability-providers/blob/main/.github/workflows/httpserver.yml#L26-L27 for the simple add of NATS before running the rust check

**Comment by autodidaddict** [comment]
@stevelr can we get the test suite passing here?

**Comment by autodidaddict** [comment]
@stevelr ping. this is still outstanding.

**Review by brooksmtownsend — APPROVED** [review]

**Pull request merged**
