### PR TITLE
Calculator Initial Effort

### PR DESCRIPTION
**Pull request by jordan-rash**
WIP for #42

### CODE REVIEW

**Comment by jordan-rash** [comment]
Looking for an assemblyscript person to build out the last example.  

Basically, requests will come in like this 
```bash
curl 'localhost:8080/add?5,5'
curl 'localhost:8080/sub?5,5'
curl 'localhost:8080/div?5,5'
```
and return
```bash
add: 5 + 5 = 10
substract: 5 - 5 = 0
divide: 5 / 5 = 1
```

Any other endpoint returns "Welcome the the wasmcloud calculator"
And if they try to divide by 0, it returns "You cant divide by 0!"

**Comment by jordan-rash** [comment]
I acknowledge that the `node_modules` being in the repo is less than ideal, but Katacoda was having some sincere issues with getting the modules installed, so I figured we could make an exception until I can get the environment working better :-)

**Comment by autodidaddict** [comment]
We should absolutely keep the node modules out of this repo. If katacoda needs node modules for a sample, then we should put the sample somewhere specific to katacoda.

**Comment by brooksmtownsend** [comment]
Agreed w/ @autodidaddict on the `node_modules` comment, it's unfortunate the struggles that Katacoda is creating here

**Comment by autodidaddict** [comment]
What about leaving node modules out and forcing an npm install during the env build? It makes baby hard seals cry when we commit node modules.

**Comment by jordan-rash** [comment]
> What about leaving node modules out and forcing an npm install during the env build? It makes baby hard seals cry when we commit node modules.

So this was the first route I went (with a global install of `asc`) and it just wasnt installing right.  That being said, this can sit here in PR for now while I try and fix it.  The tutorials are pulling from my fork ATM anyway.

**Comment by brooksmtownsend** [comment]
Hey @jordan-rash I'm gonna go ahead and close this for now as it's pretty far behind our current tooling, but if you're still interested in finishing this up just open up another PR 🙂

**Pull request closed without merging**
